ktor {
    deployment {
        port = 8080
        host = "0.0.0.0"
        port = ${?PORT}
    }
    application {
        modules = [ com.shejera.ApplicationKt.module ]
    }
}

database {
    jdbcUrl = "jdbc:postgresql://localhost:5432/shejera"
    jdbcUrl = ${?DATABASE_JDBC_URL}
    user = "shejera"
    user = ${?DATABASE_USER}
    password = "shejera"
    password = ${?DATABASE_PASSWORD}
}
